import 'package:flutter/material.dart';

const primaryColor = Color(0xffEBC76A);
const textColor = Color(0xff95989A);
const appBarColor = Color(0xffE9B673);
const conuserName = 'userNmae';
const conuserCountry = 'uesrCountry';
const conuserPhone = 'userPhone';
const conuserDialCode = 'userDialCode';
const conChatCollectios = 'chats';
const conMeseegeCollection = 'messages';
const conChatMesseges = 'text';
const conUserId = 'userId';
const conChatCreatedAt = 'createdAt';
const conUserCollectios = 'users';
const conUserImageUrl = 'userImageUrl';
const conChatUserId = 'Friendchatphone';
const conFriendUserName = 'friendName';
const conFriendPhone = 'friendPhone';
const conFriendCollection = 'friends';
const conFriendId = 'friendId';
const conChatId = 'chatId';
